#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ColPack
Version  : 1.0.10
Release  : 6
URL      : https://github.com/CSCsw/ColPack/archive/v1.0.10.tar.gz
Source0  : https://github.com/CSCsw/ColPack/archive/v1.0.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: ColPack-data = %{version}-%{release}
Requires: ColPack-lib = %{version}-%{release}
Requires: ColPack-license = %{version}-%{release}

%description
ColPack is a package comprising of implementations of algorithms for various specialized vertex coloring
problems as well as algorithms for a variety of related supporting tasks in derivative computation.

%package data
Summary: data components for the ColPack package.
Group: Data

%description data
data components for the ColPack package.


%package dev
Summary: dev components for the ColPack package.
Group: Development
Requires: ColPack-lib = %{version}-%{release}
Requires: ColPack-data = %{version}-%{release}
Provides: ColPack-devel = %{version}-%{release}
Requires: ColPack = %{version}-%{release}

%description dev
dev components for the ColPack package.


%package lib
Summary: lib components for the ColPack package.
Group: Libraries
Requires: ColPack-data = %{version}-%{release}
Requires: ColPack-license = %{version}-%{release}

%description lib
lib components for the ColPack package.


%package license
Summary: license components for the ColPack package.
Group: Default

%description license
license components for the ColPack package.


%prep
%setup -q -n ColPack-1.0.10
cd %{_builddir}/ColPack-1.0.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574811010
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static --enable-examples
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1574811010
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ColPack
cp %{_builddir}/ColPack-1.0.10/COPYING %{buildroot}/usr/share/package-licenses/ColPack/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/ColPack-1.0.10/COPYING.LESSER %{buildroot}/usr/share/package-licenses/ColPack/e203d4ef09d404fa5c03cf6590e44231665be689
%make_install
## install_append content
mkdir -p %{buildroot}/usr/share/ColPack/examples
mv  %{buildroot}/usr/examples %{buildroot}/usr/share/ColPack
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/ColPack/examples/Basic/Generate_seed_matrix_for_Hessian
/usr/share/ColPack/examples/Basic/Generate_seed_matrix_for_Jacobian
/usr/share/ColPack/examples/Basic/color_bipartite_graph_using_BipartiteGraphBicoloringInterface
/usr/share/ColPack/examples/Basic/color_bipartite_graph_using_BipartiteGraphPartialColoringInterface
/usr/share/ColPack/examples/Basic/color_graph_using_GraphColoringInterface
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADIC/01_Column_compression_and_recovery_for_Jacobian_return_ADIC_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/01_Column_compression_and_recovery_for_Jacobian_return_Row_Compressed_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/02_Column_compression_and_recovery_for_Jacobian_return_Coordinate_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/03_Column_compression_and_recovery_for_Jacobian_return_Sparse_Solvers_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/04_Row_compression_and_recovery_for_Jacobian_return_Row_Compressed_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/05_Compression_and_direct_recovery_for_Hessian_return_Row_Compressed_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/06_Compression_and_direct_recovery_for_Hessian_return_Coordinate_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/07_Compression_and_direct_recovery_for_Hessian_return_Sparse_Solvers_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/08_Compression_and_indirect_recovery_for_Hessian_return_Row_Compressed_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/09_Bidirectional_compression_and_recovery_for_Jacobian_return_Row_Compressed_Format
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/10_Column_compression_and_recovery_for_Jacobian_return_Row_Compressed_Format__unmanaged_usermem
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/11_Compression_and_direct_recovery_for_Hessian_return_Row_Compressed_Format__unmanaged_usermem
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/ADOL-C/12_Bidirectional_compression_and_recovery_for_Jacobian_return_Row_Compressed_Format__unmanaged_usermem
/usr/share/ColPack/examples/Matrix_Compression_and_Recovery/CSR/01_Column_compression_and_recovery_for_Jacobian_CSR_input_return_Row_Compressed_Format

%files dev
%defattr(-,root,root,-)
/usr/include/ColPack/BipartiteGraphBicoloring.h
/usr/include/ColPack/BipartiteGraphBicoloringInterface.h
/usr/include/ColPack/BipartiteGraphCore.h
/usr/include/ColPack/BipartiteGraphInputOutput.h
/usr/include/ColPack/BipartiteGraphOrdering.h
/usr/include/ColPack/BipartiteGraphPartialColoring.h
/usr/include/ColPack/BipartiteGraphPartialColoringInterface.h
/usr/include/ColPack/BipartiteGraphPartialOrdering.h
/usr/include/ColPack/BipartiteGraphVertexCover.h
/usr/include/ColPack/ColPackHeaders.h
/usr/include/ColPack/CoutLock.h
/usr/include/ColPack/Definitions.h
/usr/include/ColPack/DisjointSets.h
/usr/include/ColPack/File.h
/usr/include/ColPack/GraphColoring.h
/usr/include/ColPack/GraphColoringInterface.h
/usr/include/ColPack/GraphCore.h
/usr/include/ColPack/GraphInputOutput.h
/usr/include/ColPack/GraphOrdering.h
/usr/include/ColPack/HessianRecovery.h
/usr/include/ColPack/JacobianRecovery1D.h
/usr/include/ColPack/JacobianRecovery2D.h
/usr/include/ColPack/MatrixDeallocation.h
/usr/include/ColPack/Pause.h
/usr/include/ColPack/RecoveryCore.h
/usr/include/ColPack/StringTokenizer.h
/usr/include/ColPack/Timer.h
/usr/include/ColPack/command_line_parameter_processor.h
/usr/include/ColPack/current_time.h
/usr/include/ColPack/extra.h
/usr/include/ColPack/mmio.h
/usr/include/ColPack/stat.h
/usr/lib64/libColPack.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libColPack.so.0
/usr/lib64/libColPack.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ColPack/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/ColPack/e203d4ef09d404fa5c03cf6590e44231665be689
